export type Locale = 'en' | 'zh' | 'ja' | 'es'

export const LOCALES: Locale[] = ['en', 'zh', 'ja', 'es']

/** Native names shown in the language switcher. */
export const LOCALE_NAMES: Record<Locale, string> = {
  en: 'English',
  zh: '中文',
  ja: '日本語',
  es: 'Español',
}

const en = {
  'nav.about': 'About',
  'auth.login': 'Log in',
  'auth.logout': 'Log out',
  'auth.loading': '…',
  'search.placeholder': 'Search a word',
  'search.from': 'From',
  'search.to': 'To',
  'search.submit': 'Search',
  'search.sourceLang': 'Source language',
  'search.targetLang': 'Target language',
  'common.loading': 'Loading…',
  'common.seeAll': 'See all',
  'theme.lightLabel': 'Light',
  'theme.darkLabel': 'Dark',
  'theme.systemLabel': 'System',
  'lang.aria': 'Interface language',

  'home.title': 'Look up a word.',
  'home.subtitle':
    'AI-powered definitions, pronunciation, and examples — built for language learners.',
  'home.wordOfDay': 'Word of the day',
  'home.docTitle': 'Open Dictionary — AI Dictionary for Language Learners',
  'home.docDescription':
    'A clean, fast AI-powered English dictionary with pronunciation, examples, translations, and per-user history and favorites. Built for language learners.',

  'word.loading': 'Loading…',
  'word.notFoundTitle': 'We couldn\u2019t find \u201c{word}\u201d',
  'word.notFoundBody': 'Check the spelling or try a different word.',
  'word.timeoutTitle': 'The lookup timed out',
  'word.timeoutBody': 'The dictionary service is taking too long. Please try again.',
  'word.networkTitle': 'Network problem',
  'word.networkBody':
    'Couldn\u2019t reach the dictionary service. Check your connection and try again.',
  'word.errorTitle': 'Something went wrong',
  'word.errorBody': 'Please try again in a moment.',
  'word.typoTitle': '\u201c{word}\u201d looks like a typo',
  'word.typoDidYouMean': 'Did you mean',
  'word.audioUk': 'UK',
  'word.audioUs': 'US',
  'word.audioPlay': 'Play',
  'word.favRemove': 'Remove from favorites',
  'word.favAdd': 'Add to favorites',
  'word.commonMistakes': 'Common mistakes',
  'word.collocations': 'Collocations',
  'word.wordFamily': 'Word family',
  'word.source': 'Source:',
  'word.synonyms': 'Synonyms:',
  'word.docTitleFallback': '{word} — Open Dictionary',

  'sidebar.favorites': 'Favorites',
  'sidebar.favoritesEmpty': 'Star a translation to save it here.',
  'sidebar.recent': 'Recent',
  'sidebar.recentEmpty': 'Search a word to get started.',

  'history.title': 'History',
  'history.empty': 'Search a word to get started.',
  'history.docTitle': 'History — Open Dictionary',

  'about.title': 'About Open Dictionary',
  'about.docTitle': 'About — Open Dictionary',
  'about.docDescription':
    'How Open Dictionary generates definitions with AI, why there are no ads, and how to report a wrong entry.',
  'about.howTitle': 'How definitions are generated',
  'about.howP1':
    'Most entries on this site — definitions, translations, and example sentences — are generated by a large language model, not copied from a printed or licensed dictionary. When a lookup succeeds, the result is cached so the next person to look up the same word gets an instant answer instead of waiting on a new AI response.',
  'about.howP2':
    'Pronunciation audio for English words, when available, comes from the Merriam-Webster Collegiate Dictionary as a fallback, since AI models don\u2019t produce audio recordings.',
  'about.adsTitle': 'Why AI instead of ads',
  'about.adsP1':
    'Traditional online dictionaries fund themselves with ads. This site funds itself by keeping costs low: an AI-generated answer is cached once and served to everyone after that, so there\u2019s nothing to sell space to.',
  'about.wrongTitle': 'When an entry is wrong',
  'about.wrongP1a':
    'Language models make mistakes, and a wrong answer can stay cached for a long time. If a definition, translation, or example looks incorrect, use the ',
  'about.wrongReportCta': 'Report this entry',
  'about.wrongP1b':
    ' link at the bottom of any word page — it flags the entry for review. This is the main way inaccurate entries get caught in a corpus too large to check by hand.',
  'about.browseTitle': 'Browse',
  'about.browseLink': 'Browse all words alphabetically',

  'report.thanks': 'Thanks — we\u2019ll take a look.',
  'report.sending': 'Reporting…',
  'report.error': 'Couldn\u2019t send — try again',
  'report.cta': 'Report this entry',

  'moreExamples.cta': 'More examples like this',
  'moreExamples.topicPlaceholder': 'Topic (optional), e.g. football',
  'moreExamples.generating': 'Generating…',
  'moreExamples.getExamples': 'Get examples',
  'moreExamples.error': 'Couldn\u2019t generate examples — try again.',
}

export type TranslationKey = keyof typeof en
type Dictionary = Record<TranslationKey, string>

const zh: Dictionary = {
  'nav.about': '关于',
  'auth.login': '登录',
  'auth.logout': '退出登录',
  'auth.loading': '…',
  'search.placeholder': '查单词',
  'search.from': '源语言',
  'search.to': '目标语言',
  'search.submit': '搜索',
  'search.sourceLang': '源语言',
  'search.targetLang': '目标语言',
  'common.loading': '加载中…',
  'common.seeAll': '查看全部',
  'theme.lightLabel': '浅色',
  'theme.darkLabel': '深色',
  'theme.systemLabel': '跟随系统',
  'lang.aria': '界面语言',

  'home.title': '查一个词。',
  'home.subtitle': 'AI 驱动的释义、发音与例句——专为语言学习者打造。',
  'home.wordOfDay': '每日一词',
  'home.docTitle': 'Open Dictionary — 为语言学习者打造的 AI 词典',
  'home.docDescription':
    '一个简洁快速的 AI 英语词典，提供释义、发音、例句、翻译，以及个人历史记录与收藏。专为语言学习者打造。',

  'word.loading': '加载中…',
  'word.notFoundTitle': '找不到“{word}”',
  'word.notFoundBody': '检查拼写或换个词试试。',
  'word.timeoutTitle': '查询超时',
  'word.timeoutBody': '词典服务响应过慢，请重试。',
  'word.networkTitle': '网络问题',
  'word.networkBody': '无法连接词典服务,请检查网络后重试。',
  'word.errorTitle': '出错了',
  'word.errorBody': '请稍后重试。',
  'word.typoTitle': '“{word}”看起来拼错了',
  'word.typoDidYouMean': '你是不是想查',
  'word.audioUk': '英式',
  'word.audioUs': '美式',
  'word.audioPlay': '播放',
  'word.favRemove': '从收藏中移除',
  'word.favAdd': '添加到收藏',
  'word.commonMistakes': '常见错误',
  'word.collocations': '搭配',
  'word.wordFamily': '词族',
  'word.source': '来源：',
  'word.synonyms': '同义词：',
  'word.docTitleFallback': '{word} — Open Dictionary',

  'sidebar.favorites': '收藏',
  'sidebar.favoritesEmpty': '给翻译加星即可保存到这里。',
  'sidebar.recent': '最近',
  'sidebar.recentEmpty': '查个词开始使用吧。',

  'history.title': '历史记录',
  'history.empty': '查个词开始使用吧。',
  'history.docTitle': '历史记录 — Open Dictionary',

  'about.title': '关于 Open Dictionary',
  'about.docTitle': '关于 — Open Dictionary',
  'about.docDescription': 'Open Dictionary 如何用 AI 生成释义、为何没有广告,以及如何举报错误词条。',
  'about.howTitle': '释义是如何生成的',
  'about.howP1':
    '本站的大部分内容——释义、翻译和例句——由大语言模型生成,而非摘自纸质或授权词典。查询成功后,结果会被缓存,因此下一个查同一个词的人能立即得到答案,无需等待新的 AI 响应。',
  'about.howP2':
    '英语单词的发音音频(如有)来自《韦氏大学词典》作为补充,因为 AI 模型无法生成录音。',
  'about.adsTitle': '为什么用 AI 而不是广告',
  'about.adsP1':
    '传统在线词典靠广告盈利。本站通过控制成本来维持:AI 生成的答案缓存一次后即可供所有人使用,因此没有需要出售的广告位。',
  'about.wrongTitle': '如果词条有误',
  'about.wrongP1a':
    '语言模型会犯错,而错误答案可能被长期缓存。如果某个释义、翻译或例句看起来不正确,请使用任一词典页面底部的 ',
  'about.wrongReportCta': '举报此词条',
  'about.wrongP1b':
    ' 链接——它会将该词条标记待审。在语料规模过大、无法人工逐一核查的情况下,这是发现错误词条的主要方式。',
  'about.browseTitle': '浏览',
  'about.browseLink': '按字母顺序浏览所有单词',

  'report.thanks': '感谢反馈——我们会查看。',
  'report.sending': '举报中…',
  'report.error': '发送失败——请重试',
  'report.cta': '举报此词条',

  'moreExamples.cta': '更多类似例句',
  'moreExamples.topicPlaceholder': '主题(可选),例如足球',
  'moreExamples.generating': '生成中…',
  'moreExamples.getExamples': '获取例句',
  'moreExamples.error': '无法生成例句——请重试。',
}

const ja: Dictionary = {
  'nav.about': '概要',
  'auth.login': 'ログイン',
  'auth.logout': 'ログアウト',
  'auth.loading': '…',
  'search.placeholder': '単語を検索',
  'search.from': '変換元',
  'search.to': '変換先',
  'search.submit': '検索',
  'search.sourceLang': '変換元の言語',
  'search.targetLang': '変換先の言語',
  'common.loading': '読み込み中…',
  'common.seeAll': 'すべて表示',
  'theme.lightLabel': 'ライト',
  'theme.darkLabel': 'ダーク',
  'theme.systemLabel': 'システム',
  'lang.aria': '表示言語',

  'home.title': '単語を調べる。',
  'home.subtitle': 'AI による意味・発音・例文——語学学習者のために。',
  'home.wordOfDay': '今日の単語',
  'home.docTitle': 'Open Dictionary — 語学学習者のための AI 辞書',
  'home.docDescription':
    'シンプルで高速な AI 英語辞書。意味、発音、例文、翻訳、ユーザーごとの履歴とお気に入りを提供します。語学学習者のために。',

  'word.loading': '読み込み中…',
  'word.notFoundTitle': '「{word}」が見つかりません',
  'word.notFoundBody': 'スペルを確認するか、別の単語をお試しください。',
  'word.timeoutTitle': '検索がタイムアウトしました',
  'word.timeoutBody': '辞書サービスの応答に時間がかかっています。もう一度お試しください。',
  'word.networkTitle': 'ネットワークの問題',
  'word.networkBody': '辞書サービスに接続できません。接続を確認して再度お試しください。',
  'word.errorTitle': '問題が発生しました',
  'word.errorBody': 'しばらくしてからもう一度お試しください。',
  'word.typoTitle': '「{word}」はスペルミスの可能性があります',
  'word.typoDidYouMean': 'もしかして',
  'word.audioUk': '英国',
  'word.audioUs': '米国',
  'word.audioPlay': '再生',
  'word.favRemove': 'お気に入りから削除',
  'word.favAdd': 'お気に入りに追加',
  'word.commonMistakes': 'よくある間違い',
  'word.collocations': 'コロケーション',
  'word.wordFamily': '語族',
  'word.source': '出典：',
  'word.synonyms': '類義語：',
  'word.docTitleFallback': '{word} — Open Dictionary',

  'sidebar.favorites': 'お気に入り',
  'sidebar.favoritesEmpty': '翻訳に星を付けるとここに保存されます。',
  'sidebar.recent': '最近',
  'sidebar.recentEmpty': '単語を検索して始めましょう。',

  'history.title': '履歴',
  'history.empty': '単語を検索して始めましょう。',
  'history.docTitle': '履歴 — Open Dictionary',

  'about.title': 'Open Dictionary について',
  'about.docTitle': '概要 — Open Dictionary',
  'about.docDescription':
    'Open Dictionary が AI で意味を生成する仕組み、広告がない理由、誤ったエントリーの報告方法。',
  'about.howTitle': '意味の生成方法',
  'about.howP1':
    '本サイトの大部分の項目——意味、翻訳、例文——は、印刷された辞書やライセンス辞書からコピーしたものではなく、大規模言語モデルによって生成されています。検索が成功すると結果はキャッシュされ、次に同じ単語を調べる人は新しい AI の応答を待つことなく即座に答えを得られます。',
  'about.howP2':
    '英単語の発音音声は、AI モデルが録音を生成できないため、利用可能な場合にフォールバックとしてマリアム＝ウェブスター大学辞典から提供されます。',
  'about.adsTitle': '広告ではなく AI を選ぶ理由',
  'about.adsP1':
    '従来のオンライン辞書は広告で収益を得ています。本サイトはコストを低く抑えることで成り立っています:AI が生成した答えは一度キャッシュされ、その後は誰にでも提供されるため、広告枠を売るものがありません。',
  'about.wrongTitle': 'エントリーが間違っているとき',
  'about.wrongP1a':
    '言語モデルは間違いを犯し、誤った答えが長くキャッシュされることがあります。意味、翻訳、例文に誤りがあると思われる場合は、単語ページの下部にある ',
  'about.wrongReportCta': 'このエントリーを報告',
  'about.wrongP1b':
    ' リンクを使用してください——エントリーが審査のためにフラグされます。手作業では確認しきれない規模のコーパスにおいて、不正確なエントリーを見つける主な方法です。',
  'about.browseTitle': 'ブラウズ',
  'about.browseLink': 'すべての単語をアルファベット順で見る',

  'report.thanks': 'ありがとうございます——確認します。',
  'report.sending': '報告中…',
  'report.error': '送信できませんでした——もう一度お試しください',
  'report.cta': 'このエントリーを報告',

  'moreExamples.cta': 'このような例文をもっと見る',
  'moreExamples.topicPlaceholder': 'トピック(任意)、例:サッカー',
  'moreExamples.generating': '生成中…',
  'moreExamples.getExamples': '例文を取得',
  'moreExamples.error': '例文を生成できませんでした——もう一度お試しください。',
}

const es: Dictionary = {
  'nav.about': 'Acerca de',
  'auth.login': 'Iniciar sesión',
  'auth.logout': 'Cerrar sesión',
  'auth.loading': '…',
  'search.placeholder': 'Buscar una palabra',
  'search.from': 'De',
  'search.to': 'A',
  'search.submit': 'Buscar',
  'search.sourceLang': 'Idioma de origen',
  'search.targetLang': 'Idioma de destino',
  'common.loading': 'Cargando…',
  'common.seeAll': 'Ver todo',
  'theme.lightLabel': 'Claro',
  'theme.darkLabel': 'Oscuro',
  'theme.systemLabel': 'Sistema',
  'lang.aria': 'Idioma de la interfaz',

  'home.title': 'Busca una palabra.',
  'home.subtitle':
    'Definiciones, pronunciación y ejemplos con IA — pensado para estudiantes de idiomas.',
  'home.wordOfDay': 'Palabra del día',
  'home.docTitle': 'Open Dictionary — Diccionario con IA para estudiantes de idiomas',
  'home.docDescription':
    'Un diccionario de inglés con IA, limpio y rápido: definiciones, pronunciación, ejemplos, traducciones e historial y favoritos por usuario. Pensado para estudiantes de idiomas.',

  'word.loading': 'Cargando…',
  'word.notFoundTitle': 'No pudimos encontrar “{word}”',
  'word.notFoundBody': 'Revisa la ortografía o prueba con otra palabra.',
  'word.timeoutTitle': 'La búsqueda tardó demasiado',
  'word.timeoutBody': 'El servicio de diccionario está tardando mucho. Inténtalo de nuevo.',
  'word.networkTitle': 'Problema de red',
  'word.networkBody':
    'No se pudo conectar con el servicio de diccionario. Revisa tu conexión e inténtalo de nuevo.',
  'word.errorTitle': 'Algo salió mal',
  'word.errorBody': 'Inténtalo de nuevo en un momento.',
  'word.typoTitle': '“{word}” parece un error tipográfico',
  'word.typoDidYouMean': '¿Querías decir',
  'word.audioUk': 'Reino Unido',
  'word.audioUs': 'EE. UU.',
  'word.audioPlay': 'Reproducir',
  'word.favRemove': 'Quitar de favoritos',
  'word.favAdd': 'Añadir a favoritos',
  'word.commonMistakes': 'Errores comunes',
  'word.collocations': 'Colocaciones',
  'word.wordFamily': 'Familia de palabras',
  'word.source': 'Fuente:',
  'word.synonyms': 'Sinónimos:',
  'word.docTitleFallback': '{word} — Open Dictionary',

  'sidebar.favorites': 'Favoritos',
  'sidebar.favoritesEmpty': 'Marca una traducción para guardarla aquí.',
  'sidebar.recent': 'Recientes',
  'sidebar.recentEmpty': 'Busca una palabra para empezar.',

  'history.title': 'Historial',
  'history.empty': 'Busca una palabra para empezar.',
  'history.docTitle': 'Historial — Open Dictionary',

  'about.title': 'Acerca de Open Dictionary',
  'about.docTitle': 'Acerca de — Open Dictionary',
  'about.docDescription':
    'Cómo Open Dictionary genera definiciones con IA, por qué no hay anuncios y cómo informar de una entrada incorrecta.',
  'about.howTitle': 'Cómo se generan las definiciones',
  'about.howP1':
    'La mayoría de las entradas de este sitio —definiciones, traducciones y oraciones de ejemplo— las genera un modelo de lenguaje grande, no se copian de un diccionario impreso o con licencia. Cuando una búsqueda tiene éxito, el resultado se guarda en caché para que la siguiente persona que busque la misma palabra obtenga una respuesta instantánea en lugar de esperar una nueva respuesta de IA.',
  'about.howP2':
    'El audio de pronunciación de las palabras en inglés, cuando está disponible, proviene del Merriam-Webster Collegiate Dictionary como respaldo, ya que los modelos de IA no producen grabaciones de audio.',
  'about.adsTitle': '¿Por qué IA en lugar de anuncios?',
  'about.adsP1':
    'Los diccionarios en línea tradicionales se financian con anuncios. Este sitio se financia manteniendo los costos bajos: una respuesta generada por IA se almacena en caché una vez y se sirve a todos después, así que no hay nada a lo que venderle espacio.',
  'about.wrongTitle': 'Cuando una entrada es incorrecta',
  'about.wrongP1a':
    'Los modelos de lenguaje cometen errores, y una respuesta incorrecta puede permanecer en caché durante mucho tiempo. Si una definición, traducción o ejemplo parece incorrecto, usa el enlace ',
  'about.wrongReportCta': 'Reportar esta entrada',
  'about.wrongP1b':
    ' en la parte inferior de cualquier página de palabra: marca la entrada para revisión. Esta es la forma principal de detectar entradas inexactas en un corpus demasiado grande para revisarlo a mano.',
  'about.browseTitle': 'Explorar',
  'about.browseLink': 'Explorar todas las palabras alfabéticamente',

  'report.thanks': 'Gracias — lo revisaremos.',
  'report.sending': 'Reportando…',
  'report.error': 'No se pudo enviar — inténtalo de nuevo',
  'report.cta': 'Reportar esta entrada',

  'moreExamples.cta': 'Más ejemplos como este',
  'moreExamples.topicPlaceholder': 'Tema (opcional), p. ej. fútbol',
  'moreExamples.generating': 'Generando…',
  'moreExamples.getExamples': 'Obtener ejemplos',
  'moreExamples.error': 'No se pudieron generar ejemplos — inténtalo de nuevo.',
}

export const dictionaries: Record<Locale, Dictionary> = { en, zh, ja, es }
