export default function AboutPage() {
  return (
    <div className="about-page">
      <h1 className="page-title">About Open Dictionary</h1>

      <section className="about-section">
        <h2>How definitions are generated</h2>
        <p>
          Most entries on this site — definitions, translations, and example sentences — are
          generated by a large language model, not copied from a printed or licensed dictionary.
          When a lookup succeeds, the result is cached so the next person to look up the same word
          gets an instant answer instead of waiting on a new AI response.
        </p>
        <p>
          Pronunciation audio for English words, when available, comes from the Merriam-Webster
          Collegiate Dictionary as a fallback, since AI models don't produce audio recordings.
        </p>
      </section>

      <section className="about-section">
        <h2>Why AI instead of ads</h2>
        <p>
          Traditional online dictionaries fund themselves with ads. This site funds itself by
          keeping costs low: an AI-generated answer is cached once and served to everyone after
          that, so there's nothing to sell space to.
        </p>
      </section>

      <section className="about-section">
        <h2>When an entry is wrong</h2>
        <p>
          Language models make mistakes, and a wrong answer can stay cached for a long time. If a
          definition, translation, or example looks incorrect, use the <strong>Report this
          entry</strong> link at the bottom of any word page — it flags the entry for review. This
          is the main way inaccurate entries get caught in a corpus too large to check by hand.
        </p>
      </section>
    </div>
  )
}
